# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: DockerBuild
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: azure-pipelines-step.yml

- job: InstallPython
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: sudo apt-get install pip
  - script: pip install python
  
- job: always
  steps:
  - script: echo "The build has finished"
    condition: always()

- job: success
  steps:
  - script: echo "Hurrah!!!!! The build succeeded"
    condition: succeeded()

- job: failed
  steps:
  - script: echo "The build failed - Please fix it"
    condition: failed()
