# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

  jobs:
  - job: DockerHelloWorldPrep
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo Preparing to build Hello world docker!
      displayName: 'DockerHelloWorld Preparation'
    
  - job: Docker Build
    steps:
    - script: docker build -f ./Dockerfile
      displayName: 'Docker Build'

  - job: always
    steps:
    - script: echo "The build has finished"
      condition: always()

  - job: success
    steps:
    - script: echo "Hurrah!!!!! The build succeeded"
      condition: succeeded()

  - job: failed
    steps:
    - script: echo "The build failed - Please fix it"
      condition: failed()
